### ISSUE TITLE
특정 종목에 대해서 2024Q2 재무제표 추출 안되는 현상 (Traceback, TypeError)

### ISSUE THREAD

**Issue by elcsong** [josw123/dart-fss#176]
전자공시에 동일한 접수일자 2024.08.14 된 반기보고서에 대해서 
삼성전자는 Semiannual reports가 잘 추출되지만,
삼성전기는 TypeError 발생하며 추출이 안되는 현상이 나타납니다. 비단 삼성전기 뿐만아니라 몇몇 다른 종목들도 마찬가지 입니다. 확인 부탁 드립니다.

# 실행 코드
import dart_fss as dart

api_key='######################'
dart.set_api_key(api_key=api_key)
corp_list = dart.get_corp_list()
comp = corp_list.find_by_corp_name('삼성전기', exactly=True)[0]
comp.extract_fs(bgn_de='20240101', report_tp = ['half', 'quarter'])

# 에러 표시 내용
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\lib\site-packages\dart_fss\fs\extract.py", line 1488, in extract
    statements = analyze_report(report=report,
  File "C:\Users\USER\anaconda3\lib\site-packages\dart_fss\fs\extract.py", line 1332, in analyze_report
    fs_df = remove_almost_empty_columns(fs_df, min_data_number=1)
  File "C:\Users\USER\anaconda3\lib\site-packages\dart_fss\fs\extract.py", line 1300, in remove_almost_empty_columns
    new_columns = [col for col in df_tp.columns if (regex.search(col[0]) is None) or (df_tp[col].count() > min_data_number)]
  File "C:\Users\USER\anaconda3\lib\site-packages\dart_fss\fs\extract.py", line 1300, in <listcomp>
    new_columns = [col for col in df_tp.columns if (regex.search(col[0]) is None) or (df_tp[col].count() > min_data_number)]
TypeError: expected string or bytes-like object
C:\Users\USER\anaconda3\lib\site-packages\dart_fss\fs\extract.py:1517: RuntimeWarning: Unable to extract financial statements: {'rcp_no': '20240814004285', 'corp_code': '00126371', 'corp_name': '삼성전기', 'stock_code': '009150', 'corp_cls': 'Y', 'report_nm': '반기보고서 (2024.06)', 'flr_nm': '삼성전기', 'rcept_dt': '20240814', 'rm': ''}.
  warnings.warn(warnings_text, RuntimeWarning)

# 에러표시내용 - 또 다른 종목 예시
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\lib\site-packages\dart_fss\fs\extract.py", line 1488, in extract
    statements = analyze_report(report=report,
  File "C:\Users\USER\anaconda3\lib\site-packages\dart_fss\fs\extract.py", line 1332, in analyze_report
    fs_df = remove_almost_empty_columns(fs_df, min_data_number=1)
  File "C:\Users\USER\anaconda3\lib\site-packages\dart_fss\fs\extract.py", line 1300, in remove_almost_empty_columns
    new_columns = [col for col in df_tp.columns if (regex.search(col[0]) is None) or (df_tp[col].count() > min_data_number)]
  File "C:\Users\USER\anaconda3\lib\site-packages\dart_fss\fs\extract.py", line 1300, in <listcomp>
    new_columns = [col for col in df_tp.columns if (regex.search(col[0]) is None) or (df_tp[col].count() > min_data_number)]
TypeError: expected string or bytes-like object
C:\Users\USER\anaconda3\lib\site-packages\dart_fss\fs\extract.py:1517: RuntimeWarning: Unable to extract financial statements: {'rcp_no': '20240814003987', 'corp_code': '00264945', 'corp_name': '나이스정보통신', 'stock_code': '036800', 'corp_cls': 'K', 'report_nm': '반기보고서 (2024.06)', 'flr_nm': '나이스정보통신', 'rcept_dt': '20240814', 'rm': ''}.
  warnings.warn(warnings_text, RuntimeWarning)

**Comment by elcsong** [comment]
참고로 저의 dart-fss 설치버전은 0.4.10 입니다.

**Comment by josw123** [comment]
안녕하세요.

올려주신 코드를 테스트해보니 아래와 같이 오류가 발생하지 않는 것 같습니다.
![image](https://github.com/user-attachments/assets/0b4914de-a535-462f-b234-8dbadd528b2c)
결과 파일: [00126371_['half', 'quarter'].xlsx](https://github.com/user-attachments/files/16655721/00126371_.half.quarter.xlsx)

혹시 추가적인 OS정보 및 python 버전을 알려주시면 테스트 해보도록 하겠습니다.

**Comment by elcsong** [comment]
네 그러네요. 저도 아무것도 바뀐게 없는데 지금하니 제대로 되네요. 확인 감사합니다.
