### ISSUE TITLE
미등록 인증키라고 뜹니다.

### ISSUE THREAD

**Issue by simpai** [josw123/dart-fss#22]
Traceback (most recent call last):
  File "dart.py", line 5, in <module>
    dart.dart_set_api_key(api_key=api_key)
  File "/usr/local/lib/python3.7/site-packages/dart_fss/auth.py", line 9, in dart_set_api_key
    DartAuth().api_key = api_key
  File "/usr/local/lib/python3.7/site-packages/dart_fss/auth.py", line 68, in api_key
    check_err_code(**data)
  File "/usr/local/lib/python3.7/site-packages/dart_fss/errors.py", line 32, in check_err_code
    raise DartAPIError(err_code, err_msg)
dart_fss.errors.DartAPIError: Unregistered API key, 미등록 인증키

문서에 보면 XML을 사용하면 미등록인증키라고 뜬다고 되어있는데요. Json으로 하려면 코드를 어떻게 수정해야 하는지 모르겠습니다.

혹시 인증키가 OpenAPI로 바뀐 것 때문에 그럴 수 있나요?

**Comment by josw123** [comment]
안녕하세요.
기본적으로 지금 Json을 이용중에 있습니다.(xml 미지원)

Open Dart로 변경되면서 api 키가 변경되어 기존 사용중인 키만 사용가능합니다.

즉 새로 신청한 api 키로는 기존 api를 이용한 dart-fss 라이브러리 사용이 불가능합니다.

현재 open dart 지원을 위해 코드 수정중이니 작성이 완료되는데로 dart-fss 라이브러리 업데이트 하겠습니다.

**Comment by simpai** [comment]
네 감사합니다.

**Comment by josw123** [comment]
아래와 같이 최신 버전을 한번 사용하셔서 이용해 보시기 바랍니다.

##  DART-FSS v0.3.0a 
- Open DART 지원 / 신규 Open DART API Key 필요
- Documentation: https://dart-fss.readthedocs.io/en/latest/

### 설치 방법
``` bash
pip install dart-fss==0.3.0a0
```
