### ISSUE TITLE
원인을 알 수 없는 에러 발생

### ISSUE THREAD

**Issue by MoongMoong** [josw123/dart-fss#4]
fs_quarter = samsung_electronics.get_financial_statement(start_dt='20170101')
위의 함수에서 아래와 같은 에러가 발생했습니다.
__exit__ 형의 error를 처음보는데 제가 설정함에 있어서 잘못한게 있을까요.

Traceback (most recent call last):
  File "/home/jskim/home/money/financial_data_crawl_DART_master/dart_fss_test.py", line 51, in <module>
    fs_quarter = samsung_electronics.get_financial_statement(start_dt='20170101')
  File "/home/jskim/.local/lib/python3.5/site-packages/dart_fss/crp.py", line 188, in get_financial_statement
    separator=separator)
  File "/home/jskim/.local/lib/python3.5/site-packages/dart_fss/fs.py", line 454, in search_financial_statement
    last_xbrl = last_report.xbrl
  File "/home/jskim/.local/lib/python3.5/site-packages/dart_fss/reports.py", line 147, in xbrl
    self.load_xbrl()
  File "/home/jskim/.local/lib/python3.5/site-packages/dart_fss/reports.py", line 226, in load_xbrl
    xbrl = get_xbrl_from_website(self._xbrl_url)
  File "/home/jskim/.local/lib/python3.5/site-packages/dart_fss/xbrl.py", line 771, in get_xbrl_from_website
    file_path = download_file(url, path)
  File "/home/jskim/.local/lib/python3.5/site-packages/dart_fss/_utils.py", line 28, in download_file
    with requests.get(url, stream=True) as r:
AttributeError: __exit__

**Comment by josw123** [comment]
requests 라이브러리의 과거 버전에 있었던 버그 같습니다.  
pip install --U requests 혹은 pip install requests==2.21.0 을 통해
최신 버전을 설치해 주시길 바랍니다.

**Comment by MoongMoong** [comment]
빠른 응답 감사드립니다.
혹은 커스텀으로 아래와 같이 코드를 수정한 경우에도 되더라구요.
https://stackoverflow.com/questions/7447284/how-to-troubleshoot-an-attributeerror-exit-in-multiproccesing-in-python
위의 링크를 참조했었습니다.
감사합니다.
```python
def download_file(url: str, path: str) -> str:
    # with requests.get(url, stream=True) as r:
    r = requests.get(url, stream=True)
    headers = r.headers.get('Content-Disposition')
    if not re.search('attachment', headers):
        raise Exception('Invalid Data')
    total_size = int(r.headers.get('content-length', 0))
    block_size = 8192
    filename = re.findall(r'filename="(.*?)"', headers)[0]
    file_path = os.path.join(path, filename)
    with open(file_path, 'wb') as f:
        for chunk in tqdm(r.iter_content(chunk_size=block_size),
                          total=math.ceil(total_size//block_size),
                          desc='Download',
                          unit='KB', unit_scale=True):
            if chunk is not None:
                f.write(chunk)
    return file_path
```

**Comment by josw123** [comment]
테스트해보고 다른 문제가 없으면 다음버전에 올려주신 코드로 변경하도록 하겠습니다.
해결방법을 올려주신점 감사합니다.
