### ISSUE TITLE
바이온(00232089) 분기 보고서 파싱 중 에러 발생

### ISSUE THREAD

**Issue by dveamer** [josw123/dart-fss#79]
멋진 프로그램 만들어주셔서 고맙습니다.

아래와 같은 상황을 발견했습니다.

~~~
Traceback (most recent call last):
  File "execute.py", line 91, in execute_one
    fs = corp.extract_fs(bgn_de='20100101', separate=True, report_tp=['quarter'])
  File "/usr/local/lib/python3.7/site-packages/dart_fss/corp/corp.py", line 233, in extract_fs
    return extract(self.corp_code, bgn_de, end_de, fs_tp, separate, report_tp, lang, separator, dataset)
  File "/usr/local/lib/python3.7/site-packages/dart_fss/fs/extract.py", line 1340, in extract
    raise e
  File "/usr/local/lib/python3.7/site-packages/dart_fss/fs/extract.py", line 1306, in extract
    dataset=dataset)
  File "/usr/local/lib/python3.7/site-packages/dart_fss/fs/extract.py", line 1175, in analyze_report
    fs_df = analyze_html(report, fs_tp=fs_tp, separate=separate, lang=lang)
  File "/usr/local/lib/python3.7/site-packages/dart_fss/fs/extract.py", line 583, in analyze_html
    extract_results = extract_fs_table(fs_table=fs_table, fs_tp=fs_tp, separate=separate, lang=lang)
  File "/usr/local/lib/python3.7/site-packages/dart_fss/fs/extract.py", line 486, in extract_fs_table
    columns = convert_thead_into_columns(fs_tp=tp, fs_table=table, separate=separate, lang=lang)
  File "/usr/local/lib/python3.7/site-packages/dart_fss/fs/extract.py", line 255, in convert_thead_into_columns
    date_info = [datetime.strptime(date_str, '%Y%m%d') for date_str in column[0].split('-')]
  File "/usr/local/lib/python3.7/site-packages/dart_fss/fs/extract.py", line 255, in <listcomp>
    date_info = [datetime.strptime(date_str, '%Y%m%d') for date_str in column[0].split('-')]
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: ("time data 'Statement of comprehensive income(Unit: KWR)' does not match format '%Y%m%d'", "An error occurred while fetching or analyzing {'rcp_no': '20100517001320', 'corp_code': '00232089', 'corp_name': '바이온', 'stock_code': '032980', 'corp_cls': 'K', 'report_nm': '분기보고서 (2010.03)', 'flr_nm': '바이온', 'rcept_dt': '20100517', 'rm': ''}.")

~~~

**Comment by josw123** [comment]
안녕하세요.
본업과 개인적인 일로 답변이 늦어 죄송합니다.

확인해보니 바이온의 분기보고서 (2010.03)에는 포괄손익계산서가 심플한 형태로 들어가 있어서 추출이 불가능하여 생기는 문제로 생각됩니다.

![image](https://user-images.githubusercontent.com/10247774/142578614-7b0ac1ac-8820-4921-bbc5-62fc3442d46b.png)

이 문제는 warning이 발생하지 않도록 다음 버전에 적용하도록 하겠습니다. 
(데이터 추출은 의미가 없을 것 같아 데이터 추출은 하지 않는 방향으로 처리할 예정입니다)
